### 파트너 가게 등록
POST http://localhost:8080/api/v1/seller
Content-Type: application/json

{
  "name": "테스트",
  "businessNo": "1234123456",
  "email": "audrn@gmail.com"
}

### 가게 찾기
GET http://localhost:8080/api/v1/seller/1